algorithm: cifar_viewmaker
data_root: /workspace/dabs/data

debug: true

start_enc: 0
start_gen: 0
gen_every: 1
enc_every: 1
system: CIFARViewmakerSystem

disc:
  adv_loss_weight: 5
  adv_loss_weight_gen: 10
  conv_blocks: 4
  dis_skip_steps: 0
  enc_loss_weight: 5
  gan_warmup: 1
  lr: 0.0001
  r1_penalty_weight: 1.0e-05
  wgan: false

embd_dim: 512
exp:
  base_dir: /workspace/dabs/exp/models
  name: cifar_sweep
gpus: [0]

loss_params:
  objective: AdversarialSimCLRLoss
  t: 0.1
  view_maker_loss_weight: 1

model_params:
  additive: 1
  additive_budget: 0.1
  aug_proba: 1
  budget_aware: false
  clamp_views: false
  dimensions: 3
  generator_activation: relu
  multiplicative: 0
  multiplicative_budget: 0.05
  noise_dim: 100
  num_res_blocks: 3
  spectral: false
  tps: 0
  tps_budget: 0.05
  use_budget: true
  viewmaker_downsample: false

  
num_workers: null
optim:
  lr: 0.03
  momentum: 0.9
  name: sgd
  weight_decay: 0.0001

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  viewmaker_learning_rate: 0.0001
  viewmaker_optim: adam
  weight_decay: 0


trainer:
  distributed_backend: dp
  gradient_clip_val: 0
  limit_val_batches: 1.0
  max_steps: 100001 #20001
  model_checkpoint_freq: 40000
  precision: 32
  resume_from_checkpoint: null
  seed: 0
  val_check_interval: 1.0
  weights_summary: top


defaults:
  - dataset: cifar10_small
  - model: cifar_model

dataset:
  batch_size: 128 #24
  low_data: 1