algorithm: mnist_viewmaker
data_root: /workspace/dabs/data

debug: true

start_enc: 0
enc_every: 2
gen_every: 1
start_gen: 0
system: MNISTViewmakerSystem

disc:
  adv_loss_weight: 5
  adv_loss_weight_gen: 10
  conv_blocks: 4
  dis_skip_steps: 0
  enc_loss_weight: 2
  gan_warmup: 1
  lr: 0.0001
  r1_penalty_weight: 1.0e-05
  wgan: false

embd_dim: 200 #128
exp:
  base_dir: /workspace/dabs/exp/models
  name: mnist_80%
gpus: [0]

loss_params:
  objective: AdversarialSimCLRLoss
  t: 0.1
  view_maker_loss_weight: 1

model_params:
  additive: 1
  additive_budget: 0.15
  aug_proba: 1
  budget_aware: false
  clamp_views: false
  dimensions: 3
  generator_activation: relu
  multiplicative: 0
  multiplicative_budget: 0.05
  noise_dim: 100
  num_res_blocks: 3
  spectral: false
  tps: 0
  tps_budget: 0.05
  use_budget: true
  viewmaker_downsample: false

  
num_workers: null
optim:
  lr: 0.03
  momentum: 0.9
  name: sgd
  weight_decay: 0.0001

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  viewmaker_learning_rate: 0.0001
  viewmaker_optim: adam
  weight_decay: 0


trainer:
  distributed_backend: dp
  gradient_clip_val: 0
  limit_val_batches: 1.0
  max_steps: 15001
  model_checkpoint_freq: 20000
  precision: 32
  resume_from_checkpoint: null
  seed: 0
  val_check_interval: 1.0
  weights_summary: top


defaults:
  - dataset: mnist
  - model: mnist_model

dataset:
  batch_size: 256 #24
  low_data: 1