algorithm: conditional_viewmaker
data_root: /disk2/ofirb/dabs/data
gpus: [0,1]
system: ConditionalViewmakerSystem

debug: false
num_workers: null 

disc:
  adv_loss_weight: 0.1
  conv_blocks: 4
  dis_skip_steps: 0
  gan_warmup: 1
  lr: 0.0001
  r1_penalty_weight: 0.00001
  wgan: false

exp:
  base_dir: /disk2/ofirb/dabs/exp/models
  name: conditional_vm_lfw_112

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null #/disk2/ofirb/dabs/exp/models/vm_original_50%data/epoch=159-step=39999.ckpt
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_001
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 25_000

optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 0
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.001

model_params: 
  dimensions: 3
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.05
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: false
  generator_activation: relu
  spectral: False
  viewmaker_downsample: False
  use_budget: True
  aug_proba: 1


loss_params:
  view_maker_loss_weight: 1
  t: 0.07
  objective: AdversarialSimCLRLoss

defaults:
  # - dataset: cifar10_small
  # - dataset: ffhq64
  - dataset: lfw112
  # - dataset: lfw64
  - model: jit_model

dataset:
  batch_size: 90
  low_data: 1