algorithm: viewmaker
data_root: /disk2/ofirb/dabs/data
#data_root: /home/dabs_vm/data
gpus: [3]
system: ViewmakerSystem

debug: false
num_workers: null # #########

exp:
  base_dir: /home/shahafg/shared/Apple/dabs/exp/models
#  base_dir: /home/dabs_vm/shahaf/dabs/exp/models
  name: vm_orig_pamap2_spectrogram - b0.2 # #########

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_000
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 20000

optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: pamap2_spectrogram
  - model: resnet_small # #########

dataset:
  batch_size: 128 # #########

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 1e-4
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.001

model_params: 
  dimensions: 3
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.2 # #########
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: false # #########
  generator_activation: relu
  spectral: False
  viewmaker_downsample: False
  use_budget: True
  aug_proba: 1

loss_params:
  view_maker_loss_weight: 1
  t: 0.07
  objective: AdversarialSimCLRLoss
