algorithm: viewmaker_original_disc
data_root: /disk2/ofirb/dabs/data
gpus: [2]
system: OriginalViewmakerSystemDisc

debug: false
num_workers: null 

exp:
  base_dir: /disk2/ofirb/dabs/exp/models
  name: vm_original_disc

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null 
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_000
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 25000

optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 0.0001
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.001

model_params: 
  dimensions: 3
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.05
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: true
  generator_activation: relu
  spectral: False
  viewmaker_downsample: False
  use_budget: True
  aug_proba: 1

disc:
  adv_loss_weight: 0.1
  conv_blocks: 4
  dis_skip_steps: 0
  gan_warmup: 1
  lr: 0.0001
  r1_penalty_weight: 0.00001
  wgan: false

loss_params:
  view_maker_loss_weight: 1
  t: 0.07
  objective: AdversarialSimCLRLoss

defaults:
  - dataset: cifar10_small
  - model: resnet_small

dataset:
  batch_size: 128
  low_data: 1