algorithm: tama_viewmaker
data_root: /disk2/ofirb/dabs/data
#data_root: /home/dabs_vm/data
gpus: [0]
system: ViewmakerTAMA38

debug: false
num_workers: null # #########

exp:
  base_dir: /disk2/ofirb/dabs/exp/models
  name: vm_cifar_tama_dec_noise_50% # #########

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null # "/disk2/ofirb/dabs/exp/models/vm_cifar_tama_unet/epoch=51-step=19999.ckpt"
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_000
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 20000

optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: cifar10_small
  - model: resnet_small # #########

dataset:
  batch_size: 100 # #########
  low_data: 0.5

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 1e-4
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.001

model_params: 
  dimensions: 3
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.05 # #########
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: true # #########
  generator_activation: relu
  spectral: False
  viewmaker_downsample: False
  use_budget: True
  aug_proba: 1

loss_params:
  view_maker_loss_weight: 1
  t: 0.07
  objective: AdversarialSimCLRLoss
