algorithm: double_viewmaker_schyzo_freq
data_root: /disk2/ofirb/dabs/data
# data_root: /home/dabs_vm/data
gpus: [4]
system: DoubleViewmakerSchyzoFreqSystem

debug: false
num_workers: null # #########

exp:
  base_dir: /disk2/shahafg/Apple/dabs/exp/models
#  base_dir: /home/dabs_vm/shahaf/dabs/exp/models
  name: multi_vm_schyzo_freq_orig_cifar - resnet_small w0.1 # #########

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0 # #########
  limit_val_batches: 1.0
  resume_from_checkpoint: null
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_000
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 20000

optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: cifar10_small # #########
  - model: resnet_small # #########
#  - disc: tiny_p2p_disc

disc:
  lr: 0.0001
  gan_warmup: 1
  adv_loss_weight: 0.1 # #########
  wgan: false # #########
  r1_penalty_weight: 0.000001
  conv_blocks: 4
  dis_skip_steps: 0

dataset:
  batch_size: 128 # #########

optim_params:
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 1e-4
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.001

model_params:
  dimensions: 3
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.05 # #########
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: true # #########
  generator_activation: relu # #########
  spectral: False
  viewmaker_downsample: False
  use_budget: True
  aug_proba: 1
  hf_weight: 0.01
  lf_weight: 0.01

loss_params:
  view_maker_loss_weight: 1
  t: 0.07
  objective: AdversarialSimCLRLoss
