algorithm: viewmaker_transformer
data_root: /disk2/ofirb/dabs/data
gpus: [4]
system: ViewmakerTransformerSystem

debug: false
num_workers: null

exp:
  base_dir: /home/shahafg/shared/Apple/dabs/exp/models
  name: vm_full_trans_cifar10

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: "/disk2/shahaf/Apple/dabs/exp/models/vm_full_trans_cifar10/modified_616.ckpt"
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 400_000
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 20000

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: cifar10_small
  - model: transformer

dataset:
  batch_size: 128

optim_params:
  batch_size: 128
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 0.0001
  validate_freq: 1
  patience: 1000
  num_view_update: 1
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.0001

model_params:
  dimensions: 3
  out_dim: 128
  resnet: true
  resnet_version: resnet18
  resnet_small: true
  projection_head: false
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.02
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: false
  generator_activation: relu
  spectral: False
  viewmaker_downsample: False
  use_budget: True
  aug_proba: 1

loss_params:
  view_maker_loss_weight: 1
  t: 0.07
  objective: AdversarialSimCLRLoss
