dataset:
  loss: cross_entropy
  metric: accuracy
  name: traffic_sign_small_80_percent
  batch_size: 128
  num_workers: 4
  low_data: 1
model:
  name: traffic_model_80
  kwargs:
    traffic_model_path: /workspace/gtsrb_pytorch/gtsrb_stn_80.pth
data_root: /workspace/dabs/data
gpus:
- 0
algorithm: traffic_viewmaker
system: TrafficViewmakerSystem
enc_every: 1
start_enc: 0
embd_dim: 350
disc:
  adv_loss_weight: 5
  conv_blocks: 4
  dis_skip_steps: 0
  gan_warmup: 1
  lr: 0.0001
  r1_penalty_weight: 1.0e-05
  wgan: false
  adv_loss_weight_gen: 10
  enc_loss_weight: 5
debug: false
num_workers: null
exp:
  base_dir: /workspace/dabs/exp/models
  name: traffic_80_budget=0.005
trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null
  precision: 32
  max_steps: 100001
  gradient_clip_val: 0
  distributed_backend: dp
  model_checkpoint_freq: 30000
optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  momentum: 0.9
optim_params:
  learning_rate: 0.03
  momentum: 0.9
  weight_decay: 0
  viewmaker_optim: adam
  viewmaker_learning_rate: 0.0001
model_params:
  dimensions: 3
  noise_dim: 100
  num_res_blocks: 3
  additive: 1
  additive_budget: 0.005
  multiplicative: 0
  multiplicative_budget: 0.05
  tps: 0
  tps_budget: 0.05
  budget_aware: false
  clamp_views: false
  generator_activation: relu
  spectral: false
  viewmaker_downsample: false
  use_budget: true
  aug_proba: 1
loss_params:
  view_maker_loss_weight: 1
  t: 0.1
  objective: AdversarialSimCLRLoss
train_dataset:
  IN_CHANNELS: 3
