# ckpt: /disk2/ofirb/dabs/exp/models/double_vm/epoch=256-step=99999-v1.ckpt
# ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar_orig/epoch=256-step=99999.ckpt
ckpt: /disk2/ofirb/dabs/exp/models/transformer_vm/epoch=924-step=359999.ckpt
# ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar_orig_256/epoch=512-step=99999.ckpt
data_root: /disk2/ofirb/dabs/data
gpus: [2] # [5] # #######

exp:
  base_dir: /disk2/ofirb/dabs/exp/models/
  # name: double_vm_transfer_enc_coco
  # name: original_vm_transfer_enc_coco
  name: transformer_vm_transfer_enc_aircraft
  # name: original_256_vm_transfer_enc_cifar
  # name: test

num_workers: 0
debug: false # #######

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 32  # set to 16 for O1 mixed precision
  max_epochs: 100
  gradient_clip_val: 0

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  # - dataset: cifar10_small # #######
  - dataset: aircraft_small # #######
  # - dataset: mscoco_small # #######
  # - model: resnet_small  # used to set default model when no ckpt is passed in
  - model: transformer


dataset:
  batch_size: 128
  # low_data: 0.01
  low_data: 1
