ckpt:
vm_ckpt: /home/shahafg/shared/Apple/dabs/exp/models/vm_disc_cifar10/epoch=256-step=99999.ckpt
data_root: /disk2/ofirb/dabs/data
gpus: [3]
system: ViewmakerSystem
debug: false

viewmaker:
  config_path: /home/shahafg/shared/Apple/dabs/exp/models/vm_disc_cifar10/vm_config.yaml
  p: 0.7

exp:
  base_dir: /home/shahafg/shared/Apple/dabs/exp
  name: aug_transfer vm_disc cifar10 -> cifar10_small 8% p0.7

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 32  # set to 16 for O1 mixed precision
  max_epochs: 150
  gradient_clip_val: 0

optim:
  name: sgd
  lr: 0.01
  weight_decay: 0.0002
  momentum: 0.9  # only used for momentum-based optimizers
  lr_scheduler: true

defaults:
  - dataset: cifar10_small
  # - dataset: librispeech_transfer
  - model: resnet_small  # used to set default model when no ckpt is passed in


dataset:
  batch_size: 128
  low_data: 0.08
