
ckpt:
# ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar_orig/epoch=256-step=99999.ckpt
# ckpt: /disk2/ofirb/dabs/exp/models/double_vm/epoch=256-step=99999-v1.ckpt
# vm_ckpt: /disk2/ofirb/dabs/exp/models/double_vm/epoch=256-step=99999-v1.ckpt
# vm_ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar_orig/epoch=256-step=99999.ckpt
vm_ckpt:  /home/shahafg/shared/Apple/dabs/exp/models/vm_trans_cifar10/epoch=820-step=319999.ckpt
data_root: /disk2/ofirb/dabs/data
gpus: [0]
# system: DoubleViewmakerSystem
system: ViewmakerSystem
debug: false

viewmaker:
  config_path: /disk2/ofirb/dabs/exp/models/vm_cifar_orig/vm_config.yaml
  # config_path: /home/shahafg/shared/Apple/dabs/exp/models/vm_trans_cifar10/vm_config.yaml
  p: 1.0
  reroll_prob: 0

exp:
  base_dir: /disk2/ofirb/dabs/exp
  name: vm_transformer_transfer_aug_cifar

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 32  # set to 16 for O1 mixed precision
  max_epochs: 100
  gradient_clip_val: 0

optim:
  name: sgd
  lr: 0.01
  weight_decay: 0.0002
  momentum: 0.9  # only used for momentum-based optimizers
  lr_scheduler: false

defaults:
  # - dataset: vgg_flower_small
  # - dataset: mscoco_small
  - dataset: cifar10_small
  # - dataset: aircraft_small
  - model: resnet_small  # used to set default model when no ckpt is passed in


dataset:
  batch_size: 128
  # low_data: 0.1
  low_data: 1
