#ckpt: /home/shahafg/shared/Apple/dabs/exp/models/vm_trans_cifar10/epoch=820-step=319999.ckpt                    # vm trans cifar
#ckpt: "/home/shahafg/shared/Apple/dabs/exp/models/expert_cifar10 - transformer/epoch=974-step=379999.ckpt"      # expert trans cifar
ckpt: "/home/shahafg/shared/Apple/dabs/exp/models/vm_disc_cifar10/epoch=256-step=99999.ckpt"

#ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar_orig/epoch=256-step=99999.ckpt                                                 # vm orig cifar
#ckpt: "/disk2/shahafg/Apple/dabs/exp/models/double_vm_cifar10 - resnet_small (b0.05, b0.05)/epoch=256-step=99999-v1.ckpt"  # double vm cifar

#ckpt: "/home/shahafg/shared/Apple/dabs/exp/models/vm_orig_pamap - b0.05/epoch=102-step=39999.ckpt"                         # vm orig pamap
#ckpt: "/disk2/shahafg/Apple/dabs/exp/models/double_vm_pamap - resnet_small (b0.05, b0.05)/epoch=51-step=19999.ckpt"        # vm double pamap
#ckpt: "/home/dabs_vm/shahaf/dabs/exp/models/double_pamap/double_pamap_ckpt.ckpt"                                           # vm double pamap (gcp)

data_root: /disk2/ofirb/dabs/data
#data_root: /ssd/dabs_data
gpus: [2] # #######

exp:
  base_dir: /disk2/shahafg/Apple/dabs/exp/models
#  base_dir: /home/dabs_vm/shahaf/dabs/exp/models
  name: vm_disc_cifar_transfer_cifar # #######

num_workers: null
debug: false # #######

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 32  # set to 16 for O1 mixed precision
  max_epochs: 100
  gradient_clip_val: 0

model_params:
  prepool: true
  prehead: true

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: cifar10_small # #######
  - model: resnet_small  # used to set default model when no ckpt is passed in
