# ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar_orig/epoch=51-step=19999.ckpt
# ckpt: /home/shahafg/shared/Apple/dabs/exp/models/vm_trans_cifar10/epoch=820-step=319999.ckpt
ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar10/epoch=256-step=99999.ckpt
# ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar10/epoch=256-step=99999.ckpt
# ckpt: /home/shahafg/shared/Apple/dabs/exp/models/vm_disc_cifar10/epoch=256-step=99999.ckpt
data_root: /disk2/ofirb/dabs/data
gpus: [0] 

exp:
  base_dir: /disk2/ofirb/dabs/exp/models
  name: vm_transformer_cifar10_tsne 

num_workers: 0
debug: true 

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 32  # set to 16 for O1 mixed precision
  max_epochs: 100
  gradient_clip_val: 0

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: cifar10_small # #######
  # - model: resnet_small  # used to set default model when no ckpt is passed in
  - model: transformer  # used to set default model when no ckpt is passed in
