ckpt:
vm_ckpt: /disk2/ofirb/dabs/exp/models/vm_cifar10/epoch=102-step=79999.ckpt
data_root: /disk2/ofirb/dabs/data
gpus: 1
system: ViewmakerSystem
debug: true

viewmaker:
  config_path: /disk2/ofirb/dabs/exp/models/vm_cifar10/vm_config.yaml

exp:
  base_dir: /disk2/shahafg/Apple/dabs/exp/models
  name: enc_transfer_vm_tformer_normed_cifar10_small

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 32  # set to 16 for O1 mixed precision
  max_epochs: 100
  gradient_clip_val: 0

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: cifar10_small
  # - dataset: librispeech_transfer
  - model: transformer  # used to set default model when no ckpt is passed in


dataset:
  batch_size: 10
